### ISSUE TITLE
conda_build_config.yaml issue

### ISSUE THREAD

**Issue by mrakitin** [nsls-ii-forge/qulacs-feedstock#9]
This config seems to be broken, and `conda-smithy` can't rerender it:
https://github.com/nsls-ii-forge/qulacs-feedstock/blob/b8afd0011e9412703800b1c69f8b85eff00cffd5/recipe/conda_build_config.yaml#L20

The rerender error:
```py
Traceback (most recent call last):
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_smithy/cli.py", line 613, in main
    args.subcommand_func(args)
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_smithy/cli.py", line 419, in __call__
    self._call(args, tmpdir)
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_smithy/cli.py", line 430, in _call
    temporary_directory=temporary_directory,
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1953, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1221, in render_azure
    return_metadata=return_metadata,
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 627, in _render_ci_provider
    channel_urls=forge_config.get("channels", {}).get("sources", []),
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_build/api.py", line 45, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_build/render.py", line 813, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_build/variants.py", line 548, in get_package_variants
    return filter_combined_spec_to_used_keys(combined_spec, specs=specs)
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_build/variants.py", line 534, in filter_combined_spec_to_used_keys
    combined_spec = dict_of_lists_to_list_of_dicts(combined_spec, extend_keys=extend_keys)
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_build/variants.py", line 410, in dict_of_lists_to_list_of_dicts
    list(_get_zip_key_set(dict_of_lists)))
  File "/Users/mrakitin/anaconda3/envs/conda-smithy/lib/python3.7/site-packages/conda_build/variants.py", line 331, in _get_zip_key_set
    "'{}' is in more than one group.".format(_all_unique))
ValueError: All packages in zip keys must belong to only one group.  'None' is in more than one group.
```

@leofang, what was supposed to be there?

**Comment by leofang** [comment]
Thanks for catching it, @mrakitin. I have no idea! I hope it's not a regression in conda-smithy's support for self-hosted agents...Let me check locally later.

One thing to note, though, is that CF's docker images are migrated to quay.io. Not sure if the old Docker Hub ones are still working or not.

**Comment by leofang** [comment]
Sorry for getting back late, @mrakitin. Did you forget to pass `-e` when rerendering?
```
$ conda-smithy rerender -e recipe/conda_build_config.yaml 
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /home/leofang/nsls2forge/qulacs-feedstock/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/leofang/nsls2forge/qulacs-feedstock/recipe/conda_build_config.yaml
Adding in variants from argument_variants
INFO:conda_build.variants:Adding in variants from argument_variants
INFO:conda_smithy.configure_feedstock:Re-rendered with conda-build 3.20.3 and conda-smithy 3.8.6
INFO:conda_smithy.configure_feedstock:You can commit the changes with:

    git commit -m "MNT: Re-rendered with conda-build 3.20.3 and conda-smithy 3.8.6"

INFO:conda_smithy.configure_feedstock:These changes need to be pushed to github!
```

**Comment by leofang** [comment]
@mrakitin Let me close this issue, but feel free to reopen if it still bothers you, though I think I'll just archive this feedstock given our inactive usage in CSI.
